### ISSUE TITLE
Collaborative design of a DeepSensor task for SST analysis

### ISSUE THREAD

**Issue by DaniJonesOcean** [CIGLR-ai-lab/GreatLakes-TempSensors#19]
## Issue Description
We aim to design a DeepSensor `Task` that will be a building block for our SST analysis. Our `Task` needs to accurately encompass the context and target sets involving SST data. At this stage, we have not fully specified the auxiliary datasets that should be incorporated into the `Task` - we can develop this collaboratively. 

We can use the DeepSensor documentation on Tasks as guidance:

- [https://alan-turing-institute.github.io/deepsensor/user-guide/task.html](https://alan-turing-institute.github.io/deepsensor/user-guide/task.html)
- [https://alan-turing-institute.github.io/deepsensor/user-guide/task_loader.html](https://alan-turing-institute.github.io/deepsensor/user-guide/task_loader.html)

### Objectives
- [ ] Define the context and target sets for the SST DeepSensor `Task`.
- [ ] Identify and discuss which auxiliary datasets could enhance our `Task` and how they might be used.
- [ ] Generate a `Task` object with the agreed-upon context, target, and auxiliary datasets.
- [ ] Visualize the `Task` for preliminary assessments.

#### Task 1: Review and Discuss Auxiliary Dataset Options
- [ ] Compile a short list of potential auxiliary datasets (e.g. lake depth).
- [ ] Discuss the relevance and availability of each dataset and how it might integrate into the `Task`.

#### Task 2: Prepare SST Context and Target Data
- [ ] Ensure that SST data is correctly processed, handling NaN values and normalizing as appropriate using DeepSensor's data loader.
- [ ] Establish the primary SST variable as the target set for the `Task`.

#### Task 3: Setup TaskLoader with Unspecified Auxiliary Data
- [ ] Initialize `TaskLoader`, using SST as the target 

```python
# Pseudo code for initializing `TaskLoader`
from deepsensor.data import TaskLoader

# Set placeholders for context and auxiliary data to be determined
context_data_placeholder = None  # To be replaced with actual context data
auxiliary_data_placeholder = None  # To be replaced with actual auxiliary data

task_loader = TaskLoader(
    context=context_data_placeholder,
    target=sst_data,
    aux=auxiliary_data_placeholder
)
```

#### Task 4: Delegate Sub-Tasks as Needed
- [ ] Assign research tasks and acquire auxiliary datasets.
- [ ] Create sub-tasks for preprocessing of auxiliary datasets to fit DeepSensor requirements.

#### Task 5: Visualize Designed Task
- [ ] Create visualization scripts for the `Task'

```python
# Visualization script; replace 'task' and 'task_loader' with actual objects
fig = deepsensor.plot.task(task, task_loader)
plt.show()
```

### Deliverables
- A short list of auxiliary datasets and justifications for their inclusion.
- A collaborative decision on the final choice of auxiliary datasets for the `Task`.
- A `Task` object that integrates our SST data with the chosen context and auxiliary datasets.
- Visualizations demonstrating the integration and potential insights from the `Task`.

This issue will foster collaboration and strategic thinking as we refine our approach to SST sensor placement using DeepSensor.
